//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learndb
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }

        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string GenderCode { get; set; }
        public string PhotoPath { get; set; }
        public string FIO
        {
            get
            {
                return $"{FirstName} {LastName[0]}.{Patronymic[0]}.";
            }
        }
        public bool Age { 
            get 
            { 
                return (DateTime.Now.Year - Convert.ToDateTime(Birthday).Year - 1 +  
                    (DateTime.Now.Month >= Convert.ToDateTime(Birthday).Month && DateTime.Now.Day >= Convert.ToDateTime(Birthday).Day ? 1:0)) >= 18 ? true : false; 
            }

        }

        public SolidColorBrush EditColor
        {
            get
            {
                if (Convert.ToDateTime(Birthday).Year > 1990)
                    return Brushes.Green;
                else
                    return Brushes.Orange;
            }
        }

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
